
- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
    state: latest

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

