---
- hosts: all
  gather_facts: false

  tasks:
    - name: Wait for reachable host
      become: false
      wait_for:
        port: 22
        delay: 5
        connect_timeout: 5
        timeout: 360
        host: "{{ inventory_hostname }}"
      delegate_to: localhost

