
- name: check {{ prog }} exists
  ansible.builtin.stat:
    path: /usr/local/bin/{{ prog }}
  register: item_stat

- name: compile {{ prog }}
  ansible.builtin.shell:
    cmd: make -C src/{{ prog }}/
  when: not item_stat.stat.exists

- name: install {{ prog }}
  ansible.builtin.shell:
    cmd: make -C src/{{ prog }}/ install
  become: true
  when: not item_stat.stat.exists

