
- name: check src/ exists
  ansible.builtin.stat:
    path: src
  register: src_check

- name: "install src/"
  ansible.builtin.git:
    repo: https://github.com/hilbix/src.git
    dest: src
    version: 15293a58a46b0600f63fc678d0fb149210f2c1ea
    refspec: refs/heads/master
  when: not src_check.stat.exists

- name: "install extra packages"
  ansible.builtin.apt:
    name:
      - git
      - build-essential
      - tmux
  become: yes

- name: "install standard .gitconfig"
  ansible.builtin.copy:
    src: files/gitconfig
    dest: .gitconfig
    force: false
  notify: Make gitstart

- name: "install fixes"
  ansible.builtin.import_role:
    name: hilbix-fix

