
# Apparently Ansible lacks the possibility to find out the current HOME of the current USER
# https://github.com/ansible/ansible/issues/15901#issuecomment-352400456
# Note Ansible is still broken even that this bug is closed AND locked!
- name: Get current HOME
  ansible.builtin.shell: "echo $HOME"
  register: user_home
  changed_when: false
  check_mode: no

- name: "check {{ user_home.stdout }}/src/ exists"
  ansible.builtin.stat:
    path: "{{ user_home.stdout }}/src"
  register: src_check

- name: "install {{ user_home.stdout }}/src/"
  ansible.builtin.git:
    repo: https://github.com/hilbix/src.git
    dest: "{{ user_home.stdout }}/src"
    version: 15293a58a46b0600f63fc678d0fb149210f2c1ea
    refspec: refs/heads/master
  when: not src_check.stat.exists

- name: "install extra packages"
  ansible.builtin.apt:
    name:
      - git
      - build-essential
      - tmux
  become: yes

- name: "install standard .gitconfig"
  ansible.builtin.copy:
    src: files/gitconfig
    dest: "{{ user_home.stdout }}/.gitconfig"
    force: false
  notify: Make gitstart

- name: "install fixes"
  ansible.builtin.import_role:
    name: hilbix-fix

