
- name: install support packages
  ansible.builtin.apt:
    name:
      - git
      - tig
      - curl
      - telnet
      - build-essential
      - tmux
      - htop
      - psmisc
      - vim
      - vim-scripts
      - ethtool
      - jq
      - bash-completion
      - gawk
      - ifstat
      - iftop
      - hwinfo
      - iotop
      - less
      - tcpdump
      - tshark
      - debfoster
      - lsof
      - lshw
      - ltrace
      - strace
      - lvm2
      - progress
      - pwgen
      - debhelper
      - rsync
      - socat
      - sqlite3
      - sysstat
      - traceroute
      - unzip
      - p7zip
      - vnstat
      - wdiff
      - whois
      - zip
      - zstd
    state: latest
  become: yes

- ansible.builtin.import_role:
    name: apt-file

- name: install src/
  ansible.builtin.git:
    repo: https://github.com/hilbix/src.git
    dest: src
    ssh_opts: "-o StrictHostKeyChecking=accept-new"
    version: 15293a58a46b0600f63fc678d0fb149210f2c1ea
    refspec: refs/heads/master

- name: install standard .gitconfig
  ansible.builtin.copy:
    src: files/gitconfig
    dest: .gitconfig
    force: false
  notify: Make gitstart

- name: install fixes
  ansible.builtin.import_role:
    name: hilbix-fix

