
- name: install support packages
  ansible.builtin.apt:
    name:
      - git
      - tig
      - curl
      - telnet
      - build-essential
      - tmux
      - htop
      - psmisc
      - vim
      - vim-scripts
      - ethtool
      - net-tools
      - whois
      - jq
      - bash-completion
      - gawk
      - ifstat
      - iftop
      - hwinfo
      - iotop
      - less
      - tcpdump
      - tshark
      - debfoster
      - lsof
      - lshw
      - ltrace
      - strace
      - lvm2
      - progress
      - pwgen
      - debhelper
      - rsync
      - socat
      - sqlite3
      - sysstat
      - traceroute
      - unzip
      - p7zip
      - vnstat
      - wdiff
      - zip
      - zstd
    state: latest
  become: yes

- ansible.builtin.import_role:
    name: apt-file

- ansible.builtin.import_role:
    name: hilbix-src

- name: install fixes
  ansible.builtin.import_role:
    name: hilbix-fix

- name: install tools
  ansible.builtin.include_role:
    name: hilbix-src
    tasks_from: install
  vars:
    prog: "{{ item }}"
  loop:
    - count
    - dirlist
    - diskus
    - md5chk
    - mvatom
    - passfd
    - ptybuffer
    - socklinger
    - suid
    - unbuffered

