
- name: Install NetData server config
  ansible.builtin.template:
    src: templates/netdata-server/{{ item }}.conf
    dest: /etc/netdata/
    owner: root
    group: root
    mode: "0644"
  loop:
    - netdata
    - stream
    - exporting
  notify: Restart netdata

