
- hosts: ftp
  become: yes
  gather_facts: false
  roles:
  - nginx

  tasks:
  - name: Create ftp user
    ansible.builtin.user:
      name: ftp
      shell: /bin/true
      comment: ftp user
  - name: Create FTP data directory
    ansible.builtin.file:
      path: /home/ftp/ftp.sol-venetus.de
      state: directory
      mode: '2755'
      owner: ftp
      group: ftp

  - name: set authorized_keys for ftp
    ansible.posix.authorized_key:
      user: ftp
      key: "{{ lookup('file', 'files/authorized_keys/{{ item }}') }}"
    loop:
      - vahi
      - behi
      - ilba

  - name: create /etc/ssh/sshd_config.end
    ansible.builtin.file:
      path: /etc/ssh/sshd_config.end
      state: directory
      mode: '0755'
      owner: root
      group: root
  - name: add include for /etc/ssh/sshd_config.end at end of /etc/ssh/sshd_config
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      line: "Include /etc/ssh/sshd_config.end/*.conf"
      owner: root
    notify: Restart sshd
  - name: Set ftp users to sftp-internal
    ansible.builtin.copy:
      dest: /etc/ssh/sshd_config.end/sftponly.conf
      mode: '0755'
      owner: root
      group: root
      content: |
        Match group ftp
          ForceCommand internal-sftp
          ChrootDirectory %h
          PermitTunnel no
          AllowTcpForwarding no
          X11Forwarding no
    notify: Restart sshd
  - name: ssh requires /home/ftp to be owned by root:root
    ansible.builtin.file:
      path: /home/ftp/{{ item }}
      mode: '0755'
      owner: root
      group: root
    loop:
      - .
      - .ssh
  - name: own some files of /home/ftp by root:root
    ansible.builtin.file:
      path: /home/ftp/{{ item }}
      mode: '0644'
      owner: root
      group: root
    loop:
      - .ssh/authorized_keys
  - name: remove some files in /home/ftp which are of no use
    ansible.builtin.file:
      path: /home/ftp/{{ item }}
      state: absent
    loop:
      - .bashrc
      - .bash_logout
      - .profile

  - name: Create NginX config
    ansible.builtin.template:
      src: templates/nginx/ssl.authrequest
      dest: /etc/nginx/sites-enabled/{{ inventory_hostname_short }}
      owner: root
      group: root
      mode: "0755"
    vars:
      cert_ext: .proxmox.pem
      proxy_protocol: 192.168.16.254
      web_dir: ftp.sol-venetus.de
      web_dom: .sol-venetus.de
      auth_request: /_/
      auth_url: https://login.sanctuary-prime.net/___/
      autoindex: true
      per_remote_user: true
    notify: Restart nginx

  - name: create /etc/nginx/ca
    ansible.builtin.file:
      path: /etc/nginx/ca/
      state: directory
      mode: '0755'
      owner: root
      group: root
  - name: copy certificates
    ansible.builtin.copy:
      remote_src: true
      src: /home/tino/{{ item }}
      dest: /etc/nginx/ca/
    loop:
      - cacert.crt
      - "{{ inventory_hostname_short }}.proxmox.pem"
    notify: Restart nginx

  handlers:
  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted

  - name: Restart sshd
    ansible.builtin.service:
      name: sshd
      state: restarted

