
- name: Create ftp user
  ansible.builtin.user:
    name: ftp
    shell: /bin/true
    comment: ftp user

- name: Create FTP data directory
  ansible.builtin.file:
    path: /home/ftp/data
    state: directory
    mode: '2755'
    owner: ftp
    group: ftp

