
- name: "ensure directory ~{{ user }}/.ssh/{{ dir | default('keys') }} exists"
  ansible.builtin.file:
    path: "~/.ssh/{{ dir | default('keys') }}"
    state: directory
  become: true
  become_user: "{{ user }}"

- name: "create identities in .ssh/{{ dir | default('keys' }}/ for {{ user }}"
  include_tasks: ssh-id-user-key.yml
  loop: "{{ keys is string | ansible.builtin.ternary([keys], keys) }}"
  loop_control:                                                                                                                             
    loop_var: key

