# No filter named 'ansible.builtin.split, hence we do not do it here
# hence use regex_replace('^(.*)\.[^.]*$','\\1') instead

- name: "create ~{{ user }}/.ssh/{{ dir | default('.') }}/id_ identities from files/ssh-id/{{ key }}/"
  include_tasks: ssh-id-user-key-file.yml
  loop: "{{ query('ansible.builtin.fileglob', 'files/ssh-id/{{ key }}/*.key') | map('ansible.builtin.basename') | map('ansible.builtin.regex_replace', '^(.*)\\.[^.]*$','\\1') }}"
  loop_control:
    loop_var: name

