
- name: "create ~{{ user }}/.ssh/{{ dir | default('.') }}/id_{{ name }} from files/ssh-id/{{ key }}/"
  ansible.builtin.copy:
    src: "files/ssh-id/{{ key }}/{{ name }}{{ item.0 }}"
    dest: "~/.ssh/{{ dir | default('.') }}/id_{{ name }}{{ item.2 }}"
    owner: "{{ user }}"
    mode: "{{ item.1 }}"
  become: true
  become_user: "{{ user }}"
  loop:
    - [ .key, '0600', '' ]
    - [ .pub, '0644', .pub ]

