
---

- name: install docker base
  ansible.builtin.apt:
    name:
      - docker.io
    state: latest
  become: yes

- name: add docker group
  ansible.builtin.group:
    name: docker
  notify: Restart docker
  become: yes
- name: allow user to run docker
  ansible.builtin.user:
    user: tino
    groups: docker
  become: yes

